version: "3.1"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_CONN: "mongodb://mongo:27017"
      API_PORT: 3000
  mongo:
    image: mongo:4.2.5
    ports:
      - "27017:27017"